datasource:

  url: jdbc:mysql://localhost:3306/sharecom
  username: root # username
  password: 1513 # password
#  url: jdbc:mysql://sharecom-database.cvzvnmfibxbu.ap-southeast-2.rds.amazonaws.com/sharecom_database?useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
#  username: sharecom
#  password: sharecom1201


